"""empty message

Revision ID: 546321d43dfb
Revises: eb79c6df3710
Create Date: 2020-04-09 16:59:13.331498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546321d43dfb'
down_revision = 'eb79c6df3710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_image')
    # ### end Alembic commands ###
