"""empty message

Revision ID: 651c1ba0f6fd
Revises: a722c98cb111
Create Date: 2020-05-04 21:15:51.373441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651c1ba0f6fd'
down_revision = 'a722c98cb111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_image', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
