"""empty message

Revision ID: 9467ce5f062f
Revises: 
Create Date: 2020-02-17 22:28:59.487361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9467ce5f062f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('post_text', sa.String(), nullable=True),
    sa.Column('post_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
