"""Added post_preview column

Revision ID: a722c98cb111
Revises: 546321d43dfb
Create Date: 2020-05-03 22:35:39.614634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a722c98cb111'
down_revision = '546321d43dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_preview', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_preview')
    # ### end Alembic commands ###
