"""empty message

Revision ID: cdbafd9870d4
Revises: d70d96732fa6
Create Date: 2020-04-08 17:59:59.141271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbafd9870d4'
down_revision = 'd70d96732fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'comment_time')
    # ### end Alembic commands ###
