"""empty message

Revision ID: eb79c6df3710
Revises: cdbafd9870d4
Create Date: 2020-04-09 13:05:12.176337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb79c6df3710'
down_revision = 'cdbafd9870d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_image')
    # ### end Alembic commands ###
